name: dbt_consumer
version: "0.1.0"
config-version: 2

profile: dbt_consumer

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_consumer:
    marts:
      +materialized: table
